sudo: required
services:
- docker
before_install:
- curl -L https://goss.rocks/install | sudo sh
- docker build -t visibilityspots/azure-cli-terraform-vault .
script:
- docker run -ti --rm visibilityspots/azure-cli-terraform-vault az --version
- docker run -ti --rm visibilityspots/azure-cli-terraform-vault terraform --version
- docker run -ti --rm visibilityspots/azure-cli-terraform-vault vault --version
- dgoss run --name azure-cli-terraform-vault -ti visibilityspots/azure-cli-terraform-vault
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then docker login -u=visibilityspots -p="$DOCKER_PASSWORD";
  docker push visibilityspots/azure-cli-terraform-vault; fi
env:
  global:
    secure: nk7qiJcR7jkawuP/kgf8Gyr1h5XqEt8wFx131R94rW/W1pCh6a/kC4YBgFS+yvdg+kELybMB5IpgAfiuptCbjFlDJ6shi5qjgeEZdxrzcQTNQTDIxwHOLCsZ1NuEQh1/V9RDwXU/VLuhixapLJFC8WfS/cu1MbMoJ1MZyQ5gz8OsKh5nX9x7Xd7JVGLdbQ0USC2U6d0kA7zprXXCtaVbZabT0iw/eeZ+6ND1gL0fvA/7d81xlMd+tRUaN2A7a1FGUQJTsFwoSBs4xHeU+GWClTGQpQ5yPhIwvehEzD8EY5IavoLIJJvizGMCxAqGVjPgQVgh5C0y795GEmDBkJwnI5R7RV7A4FxE4Fx6Oe85hQNWjZLj1Vbtn7Vt6DBt7LLUl7I6qjbrsh2Fx4fdH8RMwKd92xYDPBP3xcMI2zh/V9r+xGIbwQXk2z0lWDSeJte+smBQ1LG/y/dju1Dx0sxrhmkHMoESYLgv2Lx6G5W4klWlbJJ2lOlO9oFhi/ZggQzpLBhfdYMH7BQaVwHOO2ZGDUvIq8TzgN4jbczgw8Ct56Fu0XFkEsCy0pWhM9Idr6X+aXzWOgkMIF/7TS3qMRBGKX+ojBW/Lyf7zJLltCXTlfXCwAYHfrvW/Qu2TccOCa6kuFXY+deTXbjwxgCpwgqwamDg11+MMntzuDmtPJkVqeU=
