name: ci

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: "0 15 * * 5"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t visibilityspots/azure-cli-terraform-vault:dev .

      - name: Install Goss
        uses: e1himself/goss-installation-action@v1.1.0
        with:
          version: 'v0.3.20'

      - name: Execute Goss tests
        run: dgoss run visibilityspots/azure-cli-terraform-vault:dev

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: visibilityspots/azure-cli-terraform-vault:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
